theme: jekyll-theme-cayman
title: "Project 3"
author: "Bryce Whitney"

<script type="text/javascript" async
src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js? 
config=TeX-MML-AM_CHTML"
</script>
